---
name: TorrServer
version: 0.0.2
slug: torrserver
description: TorrServer for home assistant
url: https://github.com/aatrubilin/hassio-torrserver
codenotary: aatrubilin@gmail.com
webui: http://[HOST]:[PORT:8090]
init: false
auth_api: true
arch:
  - amd64
ports:
  8090/tcp: 8090
