---
name: TorrServer (dev)
slug: torrserver-dev
description: TorrServer for home assistant (dev)
image: ghcr.io/aatrubilin/hassio-torrserver/{arch}
version: 1.1.2-MatriX.135-dev
url: https://github.com/aatrubilin/hassio-torrserver
codenotary: aatrubilin@gmail.com
init: false
auth_api: true
arch:
  - armv7
  - armhf
  - amd64
  - i386
  - aarch64
map:
  - addon_config:rw
options:
  httpauth: false
  logins:
    - username: homeassistant
      password: homeassistant
  pubipv4: ""
  tgtoken: ""
schema:
  httpauth: bool
  logins:
    - username: str
      password: password
  pubipv4: "str?"
  tgtoken: "str?"
ingress: true
ingress_port: 8090
ports:
  8090/tcp: 8090
ports_description:
  8090/tcp: TorrServer port
startup: system
